/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.upv.poo;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Este frame represente el menu de seleccion de herramientas
 * @author nahum
 */
public class PaintToolboxFrame extends javax.swing.JFrame {
    private final ArrayList<ToolsListener> toolsListeners = new ArrayList<>();
    /**
     * Creates new form PaintToolboxFrame2
     */
    public PaintToolboxFrame() {
        initComponents();
    }
    
    public void addToolsListener(ToolsListener l) {
        if (l != null) {
            toolsListeners.add(l);
        }
    }
     public void removeToolsListeners(ToolsListener l) {
        if (l != null) {
            toolsListeners.remove(l);
        }
    }

    private void notifyColorChanged(Color color, String colorName) {
        for (ToolsListener l : toolsListeners) {
            ColorChangedEvent e = new ColorChangedEvent(this, color, colorName);
            l.colorChanged(e);
        }
    }

    private void notifyTrazoChanged(int trazo) {
        for (ToolsListener l : toolsListeners) {
            TrazoChangedEvent e = new TrazoChangedEvent(this, trazo);
            l.trazoChanged(e);
        }
    }

    private void notifyModoChanged(int modo) {
        for (ToolsListener l : toolsListeners) {
            ModoChangedEvent e = new ModoChangedEvent(modo);
            l.modoChanged(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCcolor = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        btnColorAzul = new javax.swing.JButton();
        btnColorRojo = new javax.swing.JButton();
        lblTool = new javax.swing.JLabel();
        btnColorNegro = new javax.swing.JButton();
        jSliCambiarTexto = new javax.swing.JSlider();
        btnLibre = new javax.swing.JButton();
        btnRectangulo = new javax.swing.JButton();
        btnCirculo = new javax.swing.JButton();
        btnRecta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelCcolor.setText("Color:");

        lblSize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSize.setText("Tamaño actual del trazo: 20");
        lblSize.setToolTipText("");

        btnColorAzul.setText("Azul");
        btnColorAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorAzulActionPerformed(evt);
            }
        });

        btnColorRojo.setText("Rojo");
        btnColorRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorRojoActionPerformed(evt);
            }
        });

        lblTool.setText("Herramientas: Lapiz");

        btnColorNegro.setText("Negro");
        btnColorNegro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorNegroActionPerformed(evt);
            }
        });

        jSliCambiarTexto.setMinimum(1);
        jSliCambiarTexto.setValue(20);
        jSliCambiarTexto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliCambiarTextoStateChanged(evt);
            }
        });

        btnLibre.setText("Lapiz");
        btnLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLibreActionPerformed(evt);
            }
        });

        btnRectangulo.setText("Rectangulo");
        btnRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectanguloActionPerformed(evt);
            }
        });

        btnCirculo.setText("Circulo");
        btnCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirculoActionPerformed(evt);
            }
        });

        btnRecta.setText("Recta");
        btnRecta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSliCambiarTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblSize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnLibre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnCirculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                                    .addComponent(btnRecta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnColorNegro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(btnColorAzul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelCcolor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblTool, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnColorRojo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCcolor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnColorNegro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnColorAzul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnColorRojo)
                .addGap(22, 22, 22)
                .addComponent(lblTool)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLibre)
                    .addComponent(btnCirculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRectangulo)
                    .addComponent(btnRecta))
                .addGap(22, 22, 22)
                .addComponent(lblSize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliCambiarTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnColorAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorAzulActionPerformed
        notifyColorChanged(Color.BLUE, "Azul");
    }//GEN-LAST:event_btnColorAzulActionPerformed

    private void btnColorRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorRojoActionPerformed
       notifyColorChanged(Color.RED, "Rojo");
    }//GEN-LAST:event_btnColorRojoActionPerformed

    private void btnColorNegroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorNegroActionPerformed
         notifyColorChanged(Color.BLACK, "Negro");
    }//GEN-LAST:event_btnColorNegroActionPerformed

    private void jSliCambiarTextoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliCambiarTextoStateChanged
        try {
                int sizeTrazo = jSliCambiarTexto.getValue();
                System.out.println("Trazo: " + sizeTrazo);
                notifyTrazoChanged(sizeTrazo);
                lblSize.setText("Tamaño actual del trazo: " + sizeTrazo);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El valor del tamaño del trazo debe ser numerico y entero.");
            }
        
        
        
    }//GEN-LAST:event_jSliCambiarTextoStateChanged

    private void btnCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirculoActionPerformed
       notifyModoChanged(3);
       lblTool.setText("Herramienta: Circulo");
    }//GEN-LAST:event_btnCirculoActionPerformed

    private void btnRectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectaActionPerformed
        notifyModoChanged(2);
        lblTool.setText("Herramienta: Recta");
    }//GEN-LAST:event_btnRectaActionPerformed

    private void btnRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectanguloActionPerformed
        notifyModoChanged(4);
        lblTool.setText("Herramienta: Cuadrado");
    }//GEN-LAST:event_btnRectanguloActionPerformed

    private void btnLibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLibreActionPerformed
        notifyModoChanged(1);
        lblTool.setText("Herramienta: Lapiz");
    }//GEN-LAST:event_btnLibreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaintToolboxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaintToolboxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaintToolboxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaintToolboxFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaintToolboxFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCirculo;
    private javax.swing.JButton btnColorAzul;
    private javax.swing.JButton btnColorNegro;
    private javax.swing.JButton btnColorRojo;
    private javax.swing.JButton btnLibre;
    private javax.swing.JButton btnRecta;
    private javax.swing.JButton btnRectangulo;
    private javax.swing.JSlider jSliCambiarTexto;
    private javax.swing.JLabel labelCcolor;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblTool;
    // End of variables declaration//GEN-END:variables
}

